### PR TITLE
added /RTSSDesktopShortcut option to create RTSS desktop shortcut

### PR DESCRIPTION
**Pull request by soredake**
* **Does this PR meet the requirements:**
- [x] The commit messages are appropriate
- [x] This has been tested as far as practicable to ensure intended functionality is fine

* **What kind of change does this PR introduce?** (Bug/issue fix, new package, documentation update, etc...)
Creating RTSS desktop shortcut when /RTSSDesktopShortcut option is set.

* **What does this PR accomplish?** (Links to issues are acceptable)
Creating RTSS desktop shortcut.

* **Does this PR introduce a breaking change or require work elsewhere?**
No.

* **Other context/information**:

### CODE REVIEW

**Comment by mikeee** [comment]
Sweet, I'm going to fix the uninstall script soon. The desktop shortcut should be useful.
Didn't realise the uninstaller was currently broken and not picked up by the validator

**Review by mikeee — COMMENTED** [review]
This looks good, my only concern is that there is no removal of the shortcut afterwards. Is this something you can implement?

**Review by mikeee — CHANGES_REQUESTED** [review]
This looks good, my only concern is that there is no removal of the shortcut afterwards. Is this something you can implement?

**Comment by soredake** [comment]
@mikeee done.

**Comment by mikeee** [comment]
👍 cheers for adding this!

**Pull request merged**
